### ISSUE TITLE
chore: deprecate the repo wiki and use Docusaurus

### ISSUE THREAD

**Issue by ajhalili2006** [RecapTime/verify#5]
## Tasks

* [ ] Add deprecation notice to the wiki
* [ ] Move wiki contents to `pages/docs` directory and setup Docusaurus
* [ ] Setup GitHub Actions/GitLab CI stuff for site builds
* [ ] Finally delete everything other than the main wiki page to direct users and devs to the new docs site
